# Generated by Django 3.2.18 on 2023-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdetails_binary_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_params',
            field=models.JSONField(default=dict),
        ),
    ]
